Repository AllanOricil/chat-gpt-authenticator, pull requests merged in 2023-02, with the labels that each got.

#1 Update README
  README.md
Labels: documentation

#2 Configure CI workflow to run once a day
  .github/workflows/ci.yml
Labels: workflow

#4 Update to ES
  .babelrc
  .eslintignore
  .eslintrc.json
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .npmignore
  .prettierrc.json
  README.md
  package-lock.json
  package.json
  rollup.config.js
  src/chat-gpt-authenticator.js
  src/index.js
  test/integration/index.cjs
  test/integration/index.js
  test/integration/index.mjs
Labels: enhancement, minor

#5 Fix Release Workflow
  .github/workflows/release.yml
Labels: workflow

#6 Update rollup configuration
  .eslintignore
  package-lock.json
  package.json
  rollup.config.js
  test/integration/index.cjs
  test/integration/index.mjs
Labels: enhancement, minor

#8 Add method to exchange the session token by an access token
  src/chat-gpt-authenticator.js
  src/index.js
  test/integration/index.cjs
  test/integration/index.mjs
Labels: bug, patch

#9 Adding support for TypeScript
  package-lock.json
  package.json
  rollup.config.js
  src/index.d.ts
Labels: enhancement, minor
